import attr from '../../support/variaveis.js';
const faker = require('faker-br');
const funcao = require("./function.js")

module.exports = {
  ataDeReuniao: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('a', 'Ata de reunião').click()
    cy.contains('Consulta de Atas de reunião', { timeout: 20000 }).should('be.visible')
  },
  calendarioEscolar: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('a', 'Calendário Escolar').click()
    cy.contains('Calendário Escolar', { timeout: 20000 }).should('be.visible')
    cy.get('#AnoLetivoId').select(1)
    cy.get('#CalendarioId', { timeout: 20000 }).should('not.have.text', '   Aguarde...   ')
    cy.get('#CalendarioId').select(1)
    cy.get('#divCalendario > :nth-child(1)', { timeout: 20000 }).should('be.visible')
  },
  conteudosCurriculares: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('a', 'Conteúdos Curriculares').click()
    cy.contains('Objetos de Conhecimento', { timeout: 20000 }).should('be.visible')
    cy.get('#s2id_AnoLetivoId > .select2-choice').type(attr.dados.anoLetivo +'{enter}')
    cy.wait(1000)
    cy.get('#s2id_ComposicaoId > .select2-choice').type('Fundamental{enter}')
    cy.wait(1000)
    cy.get('#s2id_SerieId > .select2-choice').type('1º ANO{enter}')
    cy.get('#btnBuscar').click()
    cy.get('.displayGrade > :nth-child(1) > :nth-child(1)', { timeout: 20000 }).should('be.visible')
  },
  horarioProfessor: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('a', 'Horário do professor').click()
    cy.contains('Horário de aula do professor', { timeout: 20000 }).should('be.visible')
    cy.get('#btn_visualizar').click()
    cy.get('#horario', { timeout: 20000 }).should('be.visible')
  },
  elaborarPlanoEnsino: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('span', 'Turma').click()
    cy.get(attr.dados.menu3).contains('a', 'Cadastro').click()
    cy.contains('Consulta de Turmas', { timeout: 20000 }).should('be.visible')
    cy.contains('td', '1º ANO B').click()
    cy.contains('Editar Turma de Escolarização', { timeout: 20000 }).should('be.visible')
    cy.get('button.btn-expand').parent().find('button.btn-expand > i.fa.fa-book').click()
    cy.contains('Consulta de Plano de Ensino', { timeout: 20000 }).should('be.visible')
    cy.get('#s2id_GradeEscolarId > .select2-choice').type('Portug{enter}')
    cy.get('#btnElaborar > .fa').click()
    cy.contains('Elaboração do Plano de Ensino', { timeout: 20000 }).should('be.visible')
    cy.contains('Descrição').parent().find('[class="textarea"]').type('Descrição')
    cy.contains('Conclusão').parent().find('[class="textarea"]').type('Conclusão')
    cy.contains('Referências').parent().find('[class="textarea"]').type('Referências')
    cy.get('#btnPostElaborar > .fa').click()
    cy.contains('Sucesso', { timeout: 20000 }).should('be.visible')
    cy.get('.swal2-confirm').click()
    cy.get('#divElaboracoes', { timeout: 20000 }).should('be.visible')
  },
  editarElaboracaoPlanoEnsino: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('span', 'Turma').click()
    cy.get(attr.dados.menu3).contains('a', 'Cadastro').click()
    cy.contains('Consulta de Turmas', { timeout: 20000 }).should('be.visible')
    cy.contains('td', '1º ANO B').click()
    cy.contains('Editar Turma de Escolarização', { timeout: 20000 }).should('be.visible')
    cy.get('button.btn-expand').parent().find('button.btn-expand > i.fa.fa-book').click()
    cy.contains('Consulta de Plano de Ensino', { timeout: 20000 }).should('be.visible')
    // cy.get('#s2id_TurmaId > .select2-choice').type('1º ANO B{enter}')
    cy.get('#s2id_GradeEscolarId > .select2-choice').type('Portug{enter}')
    cy.get('#btnBuscar > .fa').click()
    cy.get('#divElaboracoes', { timeout: 20000 }).should('be.visible')
    cy.contains('td', 'Não Enviado').parent().find('[data-content="Visualizar/editar elaboração"]').click()
    cy.contains('Elaboração do Plano de Ensino', { timeout: 20000 }).should('be.visible')
    cy.contains('Descrição').parent().find('[class="textarea"]').clear().type('Descrição Editada')
    cy.contains('Conclusão').parent().find('[class="textarea"]').clear().type('Conclusão Editada')
    cy.contains('Referências').parent().find('[class="textarea"]').clear().type('Referências Editada')
    cy.get('#btnPostElaborar > .fa').click()
    cy.contains('Sucesso', { timeout: 20000 }).should('be.visible')
    cy.get('.swal2-confirm').click()
    cy.get('#divElaboracoes', { timeout: 20000 }).should('be.visible')
    cy.contains('td', 'Não Enviado', { timeout: 20000 }).should('be.visible')
  },
  copiarElaboracaoPlanoEnsino: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('span', 'Turma').click()
    cy.get(attr.dados.menu3).contains('a', 'Cadastro').click()
    cy.contains('Consulta de Turmas', { timeout: 20000 }).should('be.visible')
    cy.contains('td', '1º ANO B').click()
    cy.contains('Editar Turma de Escolarização', { timeout: 20000 }).should('be.visible')
    cy.get('button.btn-expand').parent().find('button.btn-expand > i.fa.fa-book').click()
    cy.contains('Consulta de Plano de Ensino', { timeout: 20000 }).should('be.visible')
    // cy.get('#s2id_TurmaId > .select2-choice').type('1º ANO B{enter}')
    cy.get('#s2id_GradeEscolarId > .select2-choice').type('Portug{enter}')
    cy.get('#btnBuscar > .fa').click()
    cy.get('#divElaboracoes', { timeout: 20000 }).should('be.visible')
    cy.contains('td', 'Não Enviado').parent().find('[data-content="Copiar essa elaboração para outras turmas"]').click()
    cy.contains('Copiar Elaboração', { timeout: 20000 }).should('be.visible')
    cy.contains('Turmas de Destino').parent().find('[class="input"]').type('1º ANO{enter}')
    cy.get('.modal-footer > .btn-primary').click()
    cy.get('.swal2-confirm').click()
  },
  excluirElaboracaoPlanoEnsino: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('span', 'Turma').click()
    cy.get(attr.dados.menu3).contains('a', 'Cadastro').click()
    cy.contains('Consulta de Turmas', { timeout: 20000 }).should('be.visible')
    cy.contains('td', '1º ANO').click()
    cy.contains('Editar Turma de Escolarização', { timeout: 20000 }).should('be.visible')
    cy.get('button.btn-expand').parent().find('button.btn-expand > i.fa.fa-book').click()
    cy.contains('Consulta de Plano de Ensino', { timeout: 20000 }).should('be.visible')
    cy.get('#s2id_GradeEscolarId > .select2-choice').type('Portug{enter}')
    cy.get('#btnBuscar > .fa').click()
    cy.get('#divElaboracoes', { timeout: 20000 }).should('be.visible')
    cy.contains('td', 'Não Enviado').parent().find('[data-content="Deletar elaboração"]').click()
    cy.contains('Atenção!', { timeout: 20000 }).should('be.visible')
    cy.get('.swal2-confirm').click()
    cy.contains('Sucesso!', { timeout: 20000 }).should('be.visible')
    cy.get('.swal2-confirm').click()
  },
  enviarElaboracaoPlanoEnsino: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('span', 'Turma').click()
    cy.get(attr.dados.menu3).contains('a', 'Cadastro').click()
    cy.contains('Consulta de Turmas', { timeout: 20000 }).should('be.visible')
    cy.contains('td', '1º ANO B').click()
    cy.contains('Editar Turma de Escolarização', { timeout: 20000 }).should('be.visible')
    cy.get('button.btn-expand').parent().find('button.btn-expand > i.fa.fa-book').click()
    cy.contains('Consulta de Plano de Ensino', { timeout: 20000 }).should('be.visible')
    cy.get('#s2id_GradeEscolarId > .select2-choice').type('Portug{enter}')
    cy.get('#btnBuscar > .fa').click()
    cy.get('#divElaboracoes', { timeout: 20000 }).should('be.visible')
    cy.contains('td', 'Não Enviado').parent().find('[data-content="Enviar elaboração para aprovação da escola"]').click()
    cy.contains('Sucesso!', { timeout: 20000 }).should('be.visible')
    cy.get('.swal2-confirm').click()
  },
  adicionarConteudoAplicado: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('span', 'Turma').click()
    cy.get(attr.dados.menu3).contains('a', 'Cadastro').click()
    cy.contains('Consulta de Turmas', { timeout: 20000 }).should('be.visible')
    // cy.contains('td', turma1).click()
    cy.contains('td', '1º ANO B').click()
    cy.contains('Editar Turma de Escolarização', { timeout: 20000 }).should('be.visible')
    cy.get('button.btn-expand').parent().find('button.btn-expand > i.fa.fa-magic').click()
    cy.contains('Registro - Conteúdo Aplicado', { timeout: 20000 }).should('be.visible')
    cy.get('#DataAula').type('Cypress.io{enter}')
    cy.get('#btnAdicionarConteudo').click()
    cy.get('#dialog_novoConteudoAplicado', { timeout: 20000 }).should('be.visible')
    cy.wait(1000)
    cy.get(':nth-child(2) > .select > #s2id_GradeEscolarId > .select2-choice', { timeout: 20000 }).should('be.visible')
    .type('PORTUGUÊS{enter}')
    cy.wait(500)
    cy.get('#s2id_TipoConteudoAplicado > .select2-choice').type('Texto{enter}')
    cy.get('#Conteudo', { timeout: 20000 }).should('be.visible').type(attr.dados.conteudoAplicado)
    cy.get('#Observacao').type(attr.dados.conteudoAplicado)
    cy.get('#btnSalvarConteudoSemHorario').click()
    cy.contains('Sucesso', { timeout: 20000 }).should('be.visible')
    cy.get('.swal2-confirm').click()
  },
  editarConteudoAplicado: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('span', 'Turma').click()
    cy.get(attr.dados.menu3).contains('a', 'Cadastro').click()
    cy.contains('Consulta de Turmas', { timeout: 20000 }).should('be.visible')
    // cy.contains('td', turma1).click()
    cy.contains('td', '1º ANO B').click()
    cy.contains('Editar Turma de Escolarização', { timeout: 20000 }).should('be.visible')
    cy.get('button.btn-expand').parent().find('button.btn-expand > i.fa.fa-magic').click()
    cy.contains('Registro - Conteúdo Aplicado', { timeout: 20000 }).should('be.visible')
    cy.wait(1000)  
    cy.get(':nth-child(1) > .select > #s2id_GradeEscolarId > .select2-choice').type('PORTUGUÊS{enter}')
    cy.get('#tabelaConteudoAplicado').should('be.visible')
    cy.contains('td','Não Enviado').parent().find('[class="btn btn-xs btn-default"]').find('i.fa.fa-edit.text-primary').click()
    cy.get('#dialog_EditarConteudoAplicado', { timeout: 20000 }).should('be.visible')
    cy.get('#Conteudo').clear().type(attr.dados.conteudoAplicadoAlterado)
    cy.get('#Observacao').clear().type(attr.dados.conteudoAplicadoAlterado)
    cy.get('#btnSalvarEdicaoConteudo').click()
    cy.contains('Sucesso', { timeout: 20000 }).should('be.visible')
  },
  enviarConteudoAplicado: function () {
    cy.get(attr.dados.menuEscola).click()
    cy.get(attr.dados.menu2).contains('span', 'Turma').click()
    cy.get(attr.dados.menu3).contains('a', 'Cadastro').click()
    cy.contains('Consulta de Turmas', { timeout: 20000 }).should('be.visible')
    // cy.contains('td', turma1).click()
    cy.contains('td', '1º ANO B').click()
    cy.contains('Editar Turma de Escolarização', { timeout: 20000 }).should('be.visible')
    cy.get('button.btn-expand').parent().find('button.btn-expand > i.fa.fa-magic').click()
    cy.contains('Registro - Conteúdo Aplicado', { timeout: 20000 }).should('be.visible')
    cy.wait(1000)  
    cy.get(':nth-child(1) > .select > #s2id_GradeEscolarId > .select2-choice').type('PORTUGUÊS{enter}')
    cy.get('#tabelaConteudoAplicado').should('be.visible')
    cy.get('#gridConteudoAplicado > .smart-form > footer > .btn').click()
    cy.get('#dialog_EnviarConteudoAplicado', { timeout: 20000 }).should('be.visible')
    cy.get('tbody > tr > .text-center').parent().find('[type="checkbox"]').click()
    cy.get('#btnEnviarConteudos').click()
    cy.contains('Sucesso', { timeout: 20000 }).should('be.visible')
  }
}
